% =========================================================================
% Practical 2: Mandelbrot-Set Serial vs Parallel Analysis
% =========================================================================
%
% GROUP NUMBER:24
%
% MEMBERS:
%   - Member 1 Nyakallo Peete, PTXNYA001
%   - Member 2 Samson  Okuthe, OKTSAM001

%% ========================================================================
%  PART 1: Mandelbrot Set Image Plotting and Saving
%  ========================================================================
%
% TODO: Implement Mandelbrot set plotting and saving function
function mandelbrot_plot(varargin) %Add necessary input arguments
    
    if nargin < 5 || isempty(out_dir)
        out_dir = "outputs";
    end

    if ~isfolder(out_dir)
        mkdir(out_dir);
    end

    fig = figure('Visible','off');
    imagesc(M);
    axis image off;
    colormap(turbo);
    colorbar;
    title(sprintf('Mandelbrot Set (%s) - %dx%d', method_name, width, height), ...
        'Interpreter','none');

    filename = fullfile(out_dir, sprintf('mandelbrot_%s_%dx%d.png', ...
        method_name, width, height));
    exportgraphics(fig, filename, 'Resolution', 200);

    close(fig);
end

%% ========================================================================
%  PART 2: Serial Mandelbrot Set Computation
%  ========================================================================`
%
%TODO: Implement serial Mandelbrot set computation function
function mandelbrot_serial(varargin) %Add necessary input arguments 
    
end

%% ========================================================================
%  PART 3: Parallel Mandelbrot Set Computation
%  ========================================================================
%
%TODO: Implement parallel Mandelbrot set computation function
function mandelbrot_parallel(varargin) %Add necessary input arguments 
    
end

%% ========================================================================
%  PART 4: Testing and Analysis
%  ========================================================================
% Compare the performance of serial Mandelbrot set computation
% with parallel Mandelbrot set computation.

function run_analysis()
    %Array conatining all the image sizes to be tested
    image_sizes = [
        [800,600],   %SVGA
        [1280,720],  %HD
        [1920,1080], %Full HD
        [2048,1080], %2K Cinema
        [2560,1440], %2K QHD
        [3840,2160], %4K UHD
        [5120,2880], %5K
        [7680,4320]  %8K UHD
    ]

    max_iterations = 1000; 
    
    %TODO: For each image size, perform the following:
    %   a. Measure execution time of mandelbrot_serial
    %   b. Measure execution time of mandelbrot_parallel
    %   c. Store results (image size, time_serial, time_parallel, speedup)  
    %   d. Plot and save the Mandelbrot set images generated by both methods
    
end